name: Publish Image

on:
  push:
    tags:
      - '*'

env:
  IMAGE_NAME: openai-discord-bot
  DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
  DOCKERHUB_PASSWORD: ${{ secrets.DOCKERHUB_PASSWORD }}

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set image tag
        id: set-tag
        run: echo ::set-output name=TAG_NAME::${{ github.ref }}

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ env.DOCKERHUB_USERNAME }}
          password: ${{ env.DOCKERHUB_PASSWORD }}

      - name: Build and push Docker image
        id: build-image
        env:
          IMAGE_NAME: ${{ env.IMAGE_NAME }}
          TAG_NAME: ${{ steps.set-tag.outputs.TAG_NAME }}
        run: |
          docker build -t $DOCKERHUB_USERNAME/$IMAGE_NAME:$TAG_NAME -t $DOCKERHUB_USERNAME/$IMAGE_NAME:latest .
          docker push $DOCKERHUB_USERNAME/$IMAGE_NAME:$TAG_NAME
          docker push $DOCKERHUB_USERNAME/$IMAGE_NAME:latest
