name: Publish Image

on:
  push:
    tags:
      - '*'

env:
  IMAGE_NAME: openai-discord-bot
  DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
  DOCKERHUB_PASSWORD: ${{ secrets.DOCKERHUB_PASSWORD }}

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set image tag
        id: set-tag
      - name: Set env
        run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ env.DOCKERHUB_USERNAME }}
          password: ${{ env.DOCKERHUB_PASSWORD }}

      - name: Build and push Docker image
        id: build-image
        env:
          IMAGE_NAME: ${{ env.IMAGE_NAME }}
        run: |
          docker build -t $DOCKERHUB_USERNAME/$IMAGE_NAME:$RELEASE_VERSION -t $DOCKERHUB_USERNAME/$IMAGE_NAME:latest .
          docker push $DOCKERHUB_USERNAME/$IMAGE_NAME:$RELEASE_VERSION
          docker push $DOCKERHUB_USERNAME/$IMAGE_NAME:latest
